// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkmgwhabyqmwxwyaubit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rbWd3aGFieXFtd3h3eWF1Yml0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MjYwMzQsImV4cCI6MjA2MzQwMjAzNH0.7TUqZdv8zFAxK6eLh577e_mwb-XQMm14zFN5V7_DMsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);